import { Metadata } from 'next'
import styles from './page.module.css'
import './globals.css'
import { Inter } from 'next/font/google'
import { Header } from '../(site)/components/Header/Header'
import { Sidebar } from '../(site)/components/Sidebar/Sidebar'
import { Footer } from '../(site)/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.wrapper}>
          <Header className={styles.header} />
          <Sidebar className={styles.sidebar} />
          <div className={styles.body}>{children}</div>
          <Footer className={styles.footer} />
        </div>
      </body>
    </html>
  )
}
