import Image from 'next/image'
import styles from './page.module.css'
import { Metadata } from 'next'
import { Button, Htag } from './components';
import Logo from '../public/vercel.svg';

// export const metadata: Metadata = {
//   title: 'Main Page',
//   description: 'Generated by create next app',
// }

export async function generateMetadata(): Promise<Metadata>{
  return{
    title: 'ComputedMeta'
  }
}

export default function Home(): JSX.Element {
  return (
    <>
    <Logo/>
      <Htag tag="h1">Text</Htag>
      <Button appearance='primary' arrow='right'>Button</Button>
      <Button appearance='ghost' arrow='down'>Button</Button>
    </>
  )
}
